stages:
  - build

variables:
  DOCKER_REGISTRY: $CI_REGISTRY
  IMAGE_NAME: $CI_REGISTRY_IMAGE

build-docker-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $IMAGE_NAME:$CI_COMMIT_SHA
      --destination $IMAGE_NAME:latest
      --cache=true
      --cache-ttl=24h
      --cache-copy-layers
      --cache-repo $IMAGE_NAME/cache
      --snapshot-mode=redo
      --compressed-caching=false
      --use-new-run
  only:
    - main
